# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
