# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_article_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
